services:
  - type: web
    name: delta-coding
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
