"""Simple local AI-like agent to generate Python project scaffolds and optionally run them.

This agent is intentionally lightweight and rule-based: it maps textual instructions
to simple project templates (Flask web app, CLI, ML scaffold, or a script). It writes
the scaffold into `generated/` and can optionally execute the main file with safety limits.
"""
import os
import re
import uuid
from . import executor


def _safe_name(name: str) -> str:
    if not name:
        return 'project_' + uuid.uuid4().hex[:6]
    s = name.strip()
    s = re.sub(r'[^a-zA-Z0-9_-]', '_', s)
    if not s:
        s = 'project_' + uuid.uuid4().hex[:6]
    return s


def _choose_template(instr_lower: str) -> str:
    if any(k in instr_lower for k in ('flask', 'web', 'api', 'server')):
        return 'flask'
    if any(k in instr_lower for k in ('cli', 'command', 'script')):
        return 'cli'
    if any(k in instr_lower for k in ('ml', 'train', 'model', 'dataset')):
        return 'ml'
    return 'script'


def generate_project(instruction: str, project_name: str = None):
    instr = (instruction or '').strip()
    template = _choose_template(instr.lower())
    name = _safe_name(project_name if project_name else (instr.split()[0] if instr else 'project'))
    files = {}

    if template == 'flask':
        files['app.py'] = f"""from flask import Flask, jsonify
app = Flask(__name__)

@app.route('/')
def index():
    return jsonify(message='Hello from {name}')

if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=8000)
"""
        files['requirements.txt'] = 'Flask>=2.0\n'
        files['README.md'] = f'# {name}\n\nGenerated Flask app. Run `python app.py`.\n'
        files['.gitignore'] = 'venv/\n__pycache__/\n*.pyc\n'

    elif template == 'cli':
        files['cli.py'] = f"""import argparse

def main():
    parser = argparse.ArgumentParser(description='CLI for {name}')
    parser.add_argument('--count', type=int, default=3)
    args = parser.parse_args()
    for i in range(args.count):
        print('Hello {name}', i)

if __name__ == '__main__':
    main()
"""
        files['README.md'] = f'# {name}\n\nGenerated CLI. Run `python cli.py --count 3`.\n'
        files['.gitignore'] = 'venv/\n__pycache__/\n*.pyc\n'

    elif template == 'ml':
        files['train.py'] = f"""# ML scaffold for {name}
print('This is a scaffold: add your training pipeline here')
"""
        files['README.md'] = f'# {name}\n\nML scaffold. Add training code and dependencies.\n'
        files['requirements.txt'] = '# add ML libs like scikit-learn, torch\n'
        files['.gitignore'] = 'venv/\n__pycache__/\n*.pyc\n'

    else:
        files['script.py'] = f"""print('Agent-generated script for {name}')
"""
        files['README.md'] = f'# {name}\n\nSimple script generated by the local agent.\n'
        files['.gitignore'] = 'venv/\n__pycache__/\n*.pyc\n'

    return name, files


def run_instruction(instruction: str, project_name: str = None, execute: bool = False, base_dir: str = None):
    base_dir = base_dir or os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'generated'))
    os.makedirs(base_dir, exist_ok=True)
    name, files = generate_project(instruction, project_name)
    project_dir = os.path.join(base_dir, name)
    if os.path.exists(project_dir):
        project_dir = project_dir + '_' + uuid.uuid4().hex[:6]
        name = os.path.basename(project_dir)
    os.makedirs(project_dir, exist_ok=True)

    for fname, content in files.items():
        with open(os.path.join(project_dir, fname), 'w') as f:
            f.write(content)

    result = {'project_name': name, 'project_path': project_dir, 'files': list(files.keys())}

    if execute:
        # pick a sensible main file
        main_file = None
        for candidate in ('app.py', 'cli.py', 'script.py', 'train.py'):
            if candidate in files:
                main_file = candidate
                break
        if not main_file:
            main_file = list(files.keys())[0]
        path = os.path.join(project_dir, main_file)
        exec_res = executor.execute_file(path, timeout=8)
        result['execution'] = exec_res

    return result
